kafka:
  consumer:
    zookeeper:
      connect: 127.0.0.1:2181
    servers: 127.0.0.1:9092
    enable:
      auto:
        commit: true
    session:
      timeout: 6000
    auto:
      commit:
        interval: 100
      offset:
        reset: latest
    topic: ylh-kafka
    group:
      id: ylh
    concurrency: 10
  producer:
    servers: 127.0.0.1:9092
    retries: 0
    batch:
      size: 4096
    linger: 1
    buffer:
      memory: 40960

  topic:
    default: ylh-kafka